table 'dw dim_deputado'
	lineageTag: de1dc532-42be-4ab0-9abc-f8d87f3157ac

	column id_deputado
		dataType: int64
		formatString: 0
		lineageTag: 42f63434-04e4-4fe0-a748-c9aa3117f7fe
		summarizeBy: none
		sourceColumn: id_deputado

		annotation SummarizationSetBy = Automatic

	column nome
		dataType: string
		lineageTag: 3617d43d-76b7-4dec-ba2b-4225ccbfd4e8
		summarizeBy: none
		sourceColumn: nome

		annotation SummarizationSetBy = Automatic

	column sexo
		dataType: string
		lineageTag: c6ee7396-45c6-4447-a7bf-0fe8c134fb42
		summarizeBy: none
		sourceColumn: sexo

		annotation SummarizationSetBy = Automatic

	column dat_nasc
		dataType: dateTime
		formatString: Long Date
		lineageTag: ed21a8a7-9b96-49ea-a1fe-0dd5fa07a427
		summarizeBy: none
		sourceColumn: dat_nasc

		variation Variation
			isDefault
			relationship: af57bd81-b480-44ab-a79e-7029f1b6a3d9
			defaultHierarchy: LocalDateTable_f9a8172c-5bf8-43f1-9bf8-3f44f2280584.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column dat_falecimento
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0f495f42-b00f-4f33-81af-dbc96abf130a
		summarizeBy: none
		sourceColumn: dat_falecimento

		variation Variation
			isDefault
			relationship: 70d8e731-feff-4434-a89c-de16a911fbf9
			defaultHierarchy: LocalDateTable_7a292228-9353-49ee-9073-dc52b006040f.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column uf_nasc
		dataType: string
		lineageTag: e597920f-5d81-4365-89c3-20d4a894e096
		summarizeBy: none
		sourceColumn: uf_nasc

		annotation SummarizationSetBy = Automatic

	column municipio_nasc
		dataType: string
		lineageTag: 0e266779-d66c-4e5c-927b-04c68debfda9
		summarizeBy: none
		sourceColumn: municipio_nasc

		annotation SummarizationSetBy = Automatic

	column data_extracao
		dataType: dateTime
		formatString: General Date
		lineageTag: 993d53a4-0625-4318-82cc-85bbcd7c76db
		summarizeBy: none
		sourceColumn: data_extracao

		variation Variation
			isDefault
			relationship: 13815aa1-e14a-4798-bf5e-cc67b73042e1
			defaultHierarchy: LocalDateTable_7756fa67-164c-4ef5-8f9e-81f651c17887.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Idade
		dataType: int64
		formatString: 0
		lineageTag: 902a8c96-c302-415d-b21f-e7b335671f4d
		summarizeBy: sum
		sourceColumn: Idade

		annotation SummarizationSetBy = Automatic

	column faixa_etaria
		dataType: string
		lineageTag: c5e38fe4-ffaa-446f-b1d7-b41b42dcc272
		summarizeBy: none
		sourceColumn: faixa_etaria
		sortByColumn: ordem_faixa

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column ordem_faixa
		dataType: int64
		formatString: 0
		lineageTag: e2bb7afa-9b52-45bc-ab94-cde31649c5eb
		summarizeBy: sum
		sourceColumn: ordem_faixa

		annotation SummarizationSetBy = Automatic

	partition 'dw dim_deputado' = m
		mode: import
		source = ```
				let
				    Fonte = PostgreSQL.Database("172.28.179.100:5432", "dw_camara"),
				    dw_dim_deputado = Fonte{[Schema="dw",Item="dim_deputado"]}[Data],
				    #"Acrescenta Idade" = Table.AddColumn(
				    dw_dim_deputado,
				    "Idade",
				    each Date.Year(DateTime.LocalNow()) - Date.Year([dat_nasc]),
				    Int64.Type
				),
				    #"Faixa Etaria" = Table.AddColumn(
				    #"Acrescenta Idade",
				    "faixa_etaria",
				    each 
				        if [Idade] < 30 then "18–29"
				        else if [Idade] < 40 then "30–39"
				        else if [Idade] < 50 then "40–49"
				        else if [Idade] < 60 then "50–59"
				        else if [Idade] < 70 then "60–69"
				        else "70+",
				    type text
				),
				    ordena = Table.AddColumn(
				    #"Faixa Etaria",
				    "ordem_faixa",
				    each 
				        if [Idade] < 30 then 1
				        else if [Idade] < 40 then 2
				        else if [Idade] < 50 then 3
				        else if [Idade] < 60 then 4
				        else if [Idade] < 70 then 5
				        else 6,
				    Int64.Type
				)
				in
				    ordena
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

